<style>
    table {
    border: medium solid #6495ed;
    border-collapse: collapse;
    width: 100%;

    }
    caption {
    font-family: monospace;
    font-size: 200%;
    margin:3%;
    }
    th {
    font-family: monospace;
    border: thin solid #6495ed;
    width: 10%;
    padding: 15px;
    background-color: #D0E3FA;

    }
    td {
    font-family: sans-serif;
    border: thin solid #6495ed;
    width: 11%;
    padding: 15px;
    text-align: center;
    background-color: #ffffff;
    }

</style>
