<style>
table {
border: medium solid #6495ed;
border-collapse: collapse;
width: 100%;

}
caption {
font-family: monospace;
font-size: 200%;
margin:3%;
}
th {
font-family: monospace;
border: thin solid #6495ed;
width: 15%;
padding: 15px;
background-color: #D0E3FA;
background-image: url(sky.jpg);
}
td {
font-family: sans-serif;
border: thin solid #6495ed;
width: 25%;
padding: 15px;
text-align: center;
background-color: #ffffff;
}
</style>
