<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="https://use.fontawesome.com/66c12c9159.js"></script>
</head>
<body>
    <nav>
        <div class="nav-wrapper grey darken-1">
            <a href="index.php" <i class="fa fa-home fa-4x" aria-hidden="true"></i></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <a href="ajout-client">Ajout Client</a>
            </ul>
        </div>
    </nav>
    <?php echo $this->layout()->content; ?>
</body>
</html>
